version: '2'
services:
  redis:
    container_name: cheat.sh-db
    image: redis:4-alpine
    restart: always
    command: "redis-server --requirepass null"
    volumes:
      - redis_data:/data

  app:
    container_name: cheat.sh
    image: cheat.sh
    restart: always
    build: .
    environment:
      - CHEATSH_CACHE_TYPE=redis
      - CHEATSH_CACHE_REDIS_HOST=redis
    #  - CHEATSH_CACHE_REDIS_PASSWORD=${REDIS_PASSWORD}
      - CHEATSH_PORT=8080
    # [DEBUG]
      - FLASK_ENV=development
    networks:
      - default
      - caddynet
    depends_on:
      - redis

volumes:
  redis_data:

networks:
  caddynet:
    external:
      name: caddynet
